name: Publish releases

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

env:
  YARN_ENABLE_GLOBAL_CACHE: false

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f  # v4.1.3
        id: release
        with:
          config-file: release-please-config.json

  npm-publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6  # v4.0.4
        with:
          node-version: lts/*

      - name: Get the Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(corepack yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
        with:
          path: ${{steps.yarn-cache-dir-path.outputs.dir}}
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-yarn-

      - name: Copy README to sub-directories
        run: |
          cp README.md packages/cli/.
          cp README.md packages/core/.

      - name: Publish to the npm registry
        run: |
          corepack yarn install --immutable
          corepack yarn build
          corepack yarn workspaces foreach --all --no-private npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
